image: docker 

stages:
  - build

build:
  stage: build
  tags:
    - gitlab-org-docker
  services: 
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Build begin"
    - docker build -t $DOCKER_IMAGE .
    - echo "Build finish"
    - docker push $DOCKER_IMAGE

  variables:
    DOCKER_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
    SA_PASSWORD: $SA_PASSWORD

