export enum CarState {
  ARRIVED = 'ARRIVED',
  DAMAGED = 'DAMAGED',
  PARKEDINSERVICE = 'PARKEDINSERVICE',
  PARKEDINSTORAGE = 'PARKEDINSTORAGE',
  PARKEDINMADTRANSPORT = 'PARKEDINMADTRANSPORT',
  PARKEDINMADCLIENT = 'PARKEDINMADCLIENT',
  OUT = 'OUT',
}
